### PR TITLE
Build with soup3 by default, support soup2

### PR DESCRIPTION
**Pull request by robert-ancell**
Fixes https://github.com/snapcore/snapd-glib/issues/115

### CODE REVIEW

**Comment by robert-ancell** [comment]
@jbicha can you review this and see if I've got it suitable for packaging?

**Comment by robert-ancell** [comment]
@aleixpol can you check if the Qt version numbers have been correctly updated? I've changed some of the directories to snapd-qt-2 and Snapd2, but I'm not sure if `/usr/include/snapd-qt-2/Snapd` should have a version number to match `/usr/lib/cmake/Snapd2`.

**Comment by aleixpol** [comment]
The change looks good to me, CC to @jriddell who is more familiar with deb/ubuntu semantics than I am.

**Comment by jbicha** [comment]
I haven't recompiled the reverse depends yet, but this merge proposal looks good enough to me.

I think bumping the API like this is useful. Thank you!

**Comment by robert-ancell** [comment]
Thanks all! Let me know if there are any issues once released and we'll fix those ASAP.

**Comment by robert-ancell** [comment]
Released in [snapd-glib 1.61](https://github.com/snapcore/snapd-glib/releases/tag/1.61)

**Pull request merged**
