### PR TITLE
Fix snapd_client_get_change_finish()

### PR DESCRIPTION
**Pull request by sergio-costas**
The function can return NULL if there is no change with that ID.

### CODE REVIEW

**Comment by sergio-costas** [comment]
The check was needed...

**Comment by robert-ancell** [comment]
Requesting an invalid ID should return an error, e.g.:
```
$ curl --unix-socket /var/run/snapd.socket http://localhost/v2/changes/1
{"type":"error","status-code":404,"status":"Not Found","result":{"message":"cannot find change with id \"1\""}}
```

So the ref change is appropriate but the documentation not?

**Comment by sergio-costas** [comment]
The point is... I receive notifications with an specific change ID, but then I ask for that ID and I receive NULL. And the way the requests are implemented, the error isn't propagated as-is, so I can only return NULL. It seems that the request doesn't generate an error that can be propagated... I'll check the source code to see if I can modify it.

**Comment by sergio-costas** [comment]
@robert-ancell Ok, now the error is propagated.

**Review by robert-ancell — APPROVED** [review]
Thanks!

**Pull request merged**
